### ISSUE TITLE
Change sentence structure !! please 

### ISSUE THREAD

**Issue by EugeneBLurn** [learn-co-curriculum/ruby-intro-to-classes-and-instances#10]
Example: "The Dog class is defined with the class keyword, followed by the class name and closed with an end. The body of this class is between the _class_ and end keywords." 
The writing through out the lessons is very confusing to me and frustrating. My version is much more clear and efficient, to me at least. 
{In Ruby we need to create a _class_ by typing an opening statement, we will name it Dog and write (syntax: class Dog) as first line. Then second line we will describe (# some code to describe a dog) our _class_ Dog followed by a third line closing the statement with (syntax: End).}
Different Dogs will require _new_ objects / instances within the _class_ to store their unique information. To call (store, memorize) a _new_ Dog object / instance we will open statement with _new_ Dog name **fido** (syntax: fido = Dog._new_) or (snoopy = Dog._new_) or (lassie = Dog._new_).
After each Dog._new_ opening statement Ruby will give us a unique identifier for that particular new Dog, instance / object. For example (syntax: snoopy = Dog._new_) Ruby will say: (syntax: snoopy #=> #<Dog:0x007fc52c2d4170>). 

I opened this issue and wrote this hoping it will help in some way. Maybe we can do an inquiry and ask other students which they relate to better. What I wrote seems much simpler, comprehensible and communicates to newbies better. Let me know what you think.

**Comment by sgharms** [comment]
@EugeneBLurn 

This seems pretty reasonable. I'm having a *bit* of trouble understanding what your desired change is exactly. Perhaps you'd consider creating a fork of this challenge, editing README.md as you see fit, and then submitting a pull request? That would allow me to see and integrate your through process very naturally. Failing that, I'll slate this challenge for a re-think.

STeven
