### ISSUE TITLE
Advanced comment out of sequence

### ISSUE THREAD

**Issue by matbalez-zz** [learn-co-curriculum/ruby-intro-to-classes-and-instances#3]
This is in the context of the qualifying track. The following content in this readme: 

"Advanced: You might notice that the #new method we are calling on the String class appears to be taking in an argument. We'll learn more about instantiating objects via #new and something called the #initialize method in an upcoming lesson."

feels odd, because the previous readme already introduced new and initialize.

**Comment by AnnJohn** [comment]
Not sure
